-- Based on:
--      https://github.com/folke/tokyonight.nvim
--      https://github.com/echasnovski/mini.colors
if vim.g.colors_name ~= nil then
  vim.cmd('highlight clear')
end
vim.g.colors_name = 'xyztokyo'

vim.api.nvim_set_hl(0, '@character.special', { link = 'SpecialChar' })
vim.api.nvim_set_hl(0, '@constant.builtin', { link = 'Special' })
vim.api.nvim_set_hl(0, '@constant.macro', { link = 'Define' })
vim.api.nvim_set_hl(0, '@constructor', { fg = '#bb9af7' })
vim.api.nvim_set_hl(0, '@constructor.tsx', { fg = '#2ac3de' })
vim.api.nvim_set_hl(0, '@field', { fg = '#73daca' })
vim.api.nvim_set_hl(0, '@function.builtin', { link = 'Special' })
vim.api.nvim_set_hl(0, '@function.call', { link = '@function' })
vim.api.nvim_set_hl(0, '@function.macro', { link = 'Macro' })
vim.api.nvim_set_hl(0, '@keyword', { fg = '#9d7cd8', italic = true })
vim.api.nvim_set_hl(0, '@keyword.coroutine', { link = '@keyword' })
vim.api.nvim_set_hl(0, '@keyword.function', { fg = '#bb9af7' })
vim.api.nvim_set_hl(0, '@keyword.operator', { link = '@operator' })
vim.api.nvim_set_hl(0, '@keyword.return', { link = '@keyword' })
vim.api.nvim_set_hl(0, '@label', { fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, '@lsp.type.boolean', { link = '@boolean' })
vim.api.nvim_set_hl(0, '@lsp.type.builtinType', { link = '@type.builtin' })
vim.api.nvim_set_hl(0, '@lsp.type.comment', { link = '@comment' })
vim.api.nvim_set_hl(0, '@lsp.type.decorator', { link = '@attribute' })
vim.api.nvim_set_hl(0, '@lsp.type.deriveHelper', { link = '@attribute' })
vim.api.nvim_set_hl(0, '@lsp.type.enum', { link = '@type' })
vim.api.nvim_set_hl(0, '@lsp.type.enumMember', { link = '@constant' })
vim.api.nvim_set_hl(0, '@lsp.type.escapeSequence', { link = '@string.escape' })
vim.api.nvim_set_hl(0, '@lsp.type.formatSpecifier', { link = '@punctuation.special' })
vim.api.nvim_set_hl(0, '@lsp.type.generic', { link = '@variable' })
vim.api.nvim_set_hl(0, '@lsp.type.interface', { fg = '#6ad5e8' })
vim.api.nvim_set_hl(0, '@lsp.type.keyword', { link = '@keyword' })
vim.api.nvim_set_hl(0, '@lsp.type.lifetime', { link = '@storageclass' })
vim.api.nvim_set_hl(0, '@lsp.type.namespace', { link = '@namespace' })
vim.api.nvim_set_hl(0, '@lsp.type.number', { link = '@number' })
vim.api.nvim_set_hl(0, '@lsp.type.operator', { link = '@operator' })
vim.api.nvim_set_hl(0, '@lsp.type.parameter', { link = '@parameter' })
vim.api.nvim_set_hl(0, '@lsp.type.property', { link = '@property' })
vim.api.nvim_set_hl(0, '@lsp.type.selfKeyword', { link = '@variable.builtin' })
vim.api.nvim_set_hl(0, '@lsp.type.selfTypeKeyword', { link = '@variable.builtin' })
vim.api.nvim_set_hl(0, '@lsp.type.string', { link = '@string' })
vim.api.nvim_set_hl(0, '@lsp.type.typeAlias', { link = '@type.definition' })
vim.api.nvim_set_hl(0, '@lsp.type.unresolvedReference', { sp = '#db4b4b', undercurl = true })
vim.api.nvim_set_hl(0, '@lsp.typemod.class.defaultLibrary', { link = '@type.builtin' })
vim.api.nvim_set_hl(0, '@lsp.typemod.enum.defaultLibrary', { link = '@type.builtin' })
vim.api.nvim_set_hl(0, '@lsp.typemod.enumMember.defaultLibrary', { link = '@constant.builtin' })
vim.api.nvim_set_hl(0, '@lsp.typemod.function.defaultLibrary', { link = '@function.builtin' })
vim.api.nvim_set_hl(0, '@lsp.typemod.keyword.async', { link = '@keyword.coroutine' })
vim.api.nvim_set_hl(0, '@lsp.typemod.keyword.injected', { link = '@keyword' })
vim.api.nvim_set_hl(0, '@lsp.typemod.macro.defaultLibrary', { link = '@function.builtin' })
vim.api.nvim_set_hl(0, '@lsp.typemod.method.defaultLibrary', { link = '@function.builtin' })
vim.api.nvim_set_hl(0, '@lsp.typemod.operator.injected', { link = '@operator' })
vim.api.nvim_set_hl(0, '@lsp.typemod.string.injected', { link = '@string' })
vim.api.nvim_set_hl(0, '@lsp.typemod.struct.defaultLibrary', { link = '@type.builtin' })
vim.api.nvim_set_hl(0, '@lsp.typemod.type.defaultLibrary', { fg = '#29a4bd' })
vim.api.nvim_set_hl(0, '@lsp.typemod.typeAlias.defaultLibrary', { fg = '#29a4bd' })
vim.api.nvim_set_hl(0, '@lsp.typemod.variable.callable', { link = '@function' })
vim.api.nvim_set_hl(0, '@lsp.typemod.variable.defaultLibrary', { link = '@variable.builtin' })
vim.api.nvim_set_hl(0, '@lsp.typemod.variable.injected', { link = '@variable' })
vim.api.nvim_set_hl(0, '@lsp.typemod.variable.static', { link = '@constant' })
vim.api.nvim_set_hl(0, '@method.call', { link = '@method' })
vim.api.nvim_set_hl(0, '@namespace', { link = 'Include' })
vim.api.nvim_set_hl(0, '@namespace.builtin', { fg = '#f7768e' })
vim.api.nvim_set_hl(0, '@operator', { fg = '#89ddff' })
vim.api.nvim_set_hl(0, '@parameter', { fg = '#e0af68' })
vim.api.nvim_set_hl(0, '@parameter.builtin', { fg = '#e6bf86' })
vim.api.nvim_set_hl(0, '@property', { fg = '#73daca' })
vim.api.nvim_set_hl(0, '@punctuation.bracket', { fg = '#a9b1d6' })
vim.api.nvim_set_hl(0, '@punctuation.delimiter', { fg = '#89ddff' })
vim.api.nvim_set_hl(0, '@punctuation.special', { fg = '#89ddff' })
vim.api.nvim_set_hl(0, '@punctuation.special.markdown', { bold = true, fg = '#ff9e64' })
vim.api.nvim_set_hl(0, '@string.documentation', { fg = '#e0af68' })
vim.api.nvim_set_hl(0, '@string.escape', { fg = '#bb9af7' })
vim.api.nvim_set_hl(0, '@string.regex', { fg = '#b4f9f8' })
vim.api.nvim_set_hl(0, '@string.special', { link = 'SpecialChar' })
vim.api.nvim_set_hl(0, '@tag.attribute', { link = '@property' })
vim.api.nvim_set_hl(0, '@tag.delimiter', { link = 'Delimiter' })
vim.api.nvim_set_hl(0, '@tag.delimiter.tsx', { fg = '#607dbf' })
vim.api.nvim_set_hl(0, '@tag.tsx', { fg = '#f7768e' })
vim.api.nvim_set_hl(0, '@text.danger', { bg = '#db4b4b', fg = '#24283b' })
vim.api.nvim_set_hl(0, '@text.diff.add', { link = 'DiffAdd' })
vim.api.nvim_set_hl(0, '@text.diff.delete', { link = 'DiffDelete' })
vim.api.nvim_set_hl(0, '@text.emphasis', { italic = true })
vim.api.nvim_set_hl(0, '@text.environment', { link = 'Macro' })
vim.api.nvim_set_hl(0, '@text.environment.name', { link = 'Type' })
vim.api.nvim_set_hl(0, '@text.literal', { link = 'String' })
vim.api.nvim_set_hl(0, '@text.literal.markdown_inline', { bg = '#414868', fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, '@text.math', { link = 'Special' })
vim.api.nvim_set_hl(0, '@text.note', { link = 'SpecialComment' })
vim.api.nvim_set_hl(0, '@text.reference', { fg = '#1abc9c' })
vim.api.nvim_set_hl(0, '@text.strike', { strikethrough = true })
vim.api.nvim_set_hl(0, '@text.strong', { bold = true })
vim.api.nvim_set_hl(0, '@text.title', { link = 'Title' })
vim.api.nvim_set_hl(0, '@text.title.1.markdown', { bold = true, fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, '@text.title.2.markdown', { bold = true, fg = '#e0af68' })
vim.api.nvim_set_hl(0, '@text.title.3.markdown', { bold = true, fg = '#9ece6a' })
vim.api.nvim_set_hl(0, '@text.title.4.markdown', { bold = true, fg = '#1abc9c' })
vim.api.nvim_set_hl(0, '@text.title.5.markdown', { bold = true, fg = '#bb9af7' })
vim.api.nvim_set_hl(0, '@text.title.6.markdown', { bold = true, fg = '#9d7cd8' })
vim.api.nvim_set_hl(0, '@text.todo', { link = 'Todo' })
vim.api.nvim_set_hl(0, '@text.todo.checked', { fg = '#73daca' })
vim.api.nvim_set_hl(0, '@text.todo.unchecked', { fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, '@text.underline', { underline = true })
vim.api.nvim_set_hl(0, '@text.uri', { link = 'Underlined' })
vim.api.nvim_set_hl(0, '@text.warning', { bg = '#e0af68', fg = '#24283b' })
vim.api.nvim_set_hl(0, '@type.builtin', { fg = '#29a4bd' })
vim.api.nvim_set_hl(0, '@type.definition', { link = 'Typedef' })
vim.api.nvim_set_hl(0, '@type.qualifier', { link = '@keyword' })
vim.api.nvim_set_hl(0, '@variable', { fg = '#c0caf5' })
vim.api.nvim_set_hl(0, '@variable.builtin', { fg = '#f7768e' })
vim.api.nvim_set_hl(0, 'Bold', { bold = true })
vim.api.nvim_set_hl(0, 'Character', { fg = '#9ece6a' })
vim.api.nvim_set_hl(0, 'CodeBlock', { bg = '#1f2335' })
vim.api.nvim_set_hl(0, 'ColorColumn', { bg = '#1d202f' })
vim.api.nvim_set_hl(0, 'Comment', { fg = '#565f89', italic = true })
vim.api.nvim_set_hl(0, 'Conceal', { fg = '#737aa2' })
vim.api.nvim_set_hl(0, 'Constant', { fg = '#ff9e64' })
vim.api.nvim_set_hl(0, 'CurSearch', { link = 'IncSearch' })
vim.api.nvim_set_hl(0, 'Cursor', { bg = '#c0caf5', fg = '#24283b' })
vim.api.nvim_set_hl(0, 'CursorColumn', { bg = '#292e42' })
vim.api.nvim_set_hl(0, 'CursorIM', { bg = '#c0caf5', fg = '#24283b' })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = '#292e42' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#737aa2' })
vim.api.nvim_set_hl(0, 'DapStoppedLine', { bg = '#373640' })
vim.api.nvim_set_hl(0, 'DapUIBreakpointsCurrentLine', { bold = true, fg = '#a9ff68' })
vim.api.nvim_set_hl(0, 'DapUIBreakpointsDisabledLine', { fg = '#424242' })
vim.api.nvim_set_hl(0, 'DapUIBreakpointsInfo', { fg = '#a9ff68' })
vim.api.nvim_set_hl(0, 'DapUIBreakpointsPath', { fg = '#00f1f5' })
vim.api.nvim_set_hl(0, 'DapUIDecoration', { fg = '#00f1f5' })
vim.api.nvim_set_hl(0, 'DapUIFloatBorder', { fg = '#00f1f5' })
vim.api.nvim_set_hl(0, 'DapUILineNumber', { fg = '#00f1f5' })
vim.api.nvim_set_hl(0, 'DapUIModifiedValue', { bold = true, fg = '#00f1f5' })
vim.api.nvim_set_hl(0, 'DapUIPlayPause', { fg = '#a9ff68' })
vim.api.nvim_set_hl(0, 'DapUIPlayPauseNC', { fg = '#a9ff68' })
vim.api.nvim_set_hl(0, 'DapUIRestart', { fg = '#a9ff68' })
vim.api.nvim_set_hl(0, 'DapUIRestartNC', { fg = '#a9ff68' })
vim.api.nvim_set_hl(0, 'DapUIScope', { fg = '#00f1f5' })
vim.api.nvim_set_hl(0, 'DapUISource', { fg = '#d484ff' })
vim.api.nvim_set_hl(0, 'DapUIStepBack', { fg = '#00f1f5' })
vim.api.nvim_set_hl(0, 'DapUIStepBackNC', { fg = '#00f1f5' })
vim.api.nvim_set_hl(0, 'DapUIStepInto', { fg = '#00f1f5' })
vim.api.nvim_set_hl(0, 'DapUIStepIntoNC', { fg = '#00f1f5' })
vim.api.nvim_set_hl(0, 'DapUIStepOut', { fg = '#00f1f5' })
vim.api.nvim_set_hl(0, 'DapUIStepOutNC', { fg = '#00f1f5' })
vim.api.nvim_set_hl(0, 'DapUIStepOver', { fg = '#00f1f5' })
vim.api.nvim_set_hl(0, 'DapUIStepOverNC', { fg = '#00f1f5' })
vim.api.nvim_set_hl(0, 'DapUIStop', { fg = '#f70067' })
vim.api.nvim_set_hl(0, 'DapUIStopNC', { fg = '#f70067' })
vim.api.nvim_set_hl(0, 'DapUIStoppedThread', { fg = '#00f1f5' })
vim.api.nvim_set_hl(0, 'DapUIThread', { fg = '#a9ff68' })
vim.api.nvim_set_hl(0, 'DapUIType', { fg = '#d484ff' })
vim.api.nvim_set_hl(0, 'DapUIUnavailable', { fg = '#424242' })
vim.api.nvim_set_hl(0, 'DapUIUnavailableNC', { fg = '#424242' })
vim.api.nvim_set_hl(0, 'DapUIWatchesEmpty', { fg = '#f70067' })
vim.api.nvim_set_hl(0, 'DapUIWatchesError', { fg = '#f70067' })
vim.api.nvim_set_hl(0, 'DapUIWatchesValue', { fg = '#a9ff68' })
vim.api.nvim_set_hl(0, 'DapUIWinSelect', { bold = true, ctermfg = 14, fg = '#00f1f5' })
vim.api.nvim_set_hl(0, 'Debug', { fg = '#ff9e64' })
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '#db4b4b' })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = '#1abc9c' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = '#0db9d7' })
vim.api.nvim_set_hl(0, 'DiagnosticInformation', { link = 'DiagnosticInfo' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineError', { sp = '#db4b4b', undercurl = true })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineHint', { sp = '#1abc9c', undercurl = true })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineInfo', { sp = '#0db9d7', undercurl = true })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineWarn', { sp = '#e0af68', undercurl = true })
vim.api.nvim_set_hl(0, 'DiagnosticUnnecessary', { fg = '#414868' })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextError', { bg = '#362c3d', fg = '#db4b4b' })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextHint', { bg = '#233745', fg = '#1abc9c' })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextInfo', { bg = '#22374b', fg = '#0db9d7' })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextWarn', { bg = '#373640', fg = '#e0af68' })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingError', { bg = '#362c3d', fg = '#db4b4b' })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingHint', { bg = '#233745', fg = '#1abc9c' })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingInfo', { bg = '#22374b', fg = '#0db9d7' })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingWarn', { bg = '#373640', fg = '#e0af68' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = '#e0af68' })
vim.api.nvim_set_hl(0, 'DiagnosticWarning', { link = 'DiagnosticWarn' })
vim.api.nvim_set_hl(0, 'DiffAdd', { bg = '#283b4d' })
vim.api.nvim_set_hl(0, 'DiffChange', { bg = '#272d43' })
vim.api.nvim_set_hl(0, 'DiffDelete', { bg = '#3f2d3d' })
vim.api.nvim_set_hl(0, 'DiffText', { bg = '#394b70' })
vim.api.nvim_set_hl(0, 'DiffviewDiffAddAsDelete', { bg = '#3f2d3d' })
vim.api.nvim_set_hl(0, 'DiffviewDim1', { fg = '#565f89' })
vim.api.nvim_set_hl(0, 'DiffviewFilePanelCounter', { bold = true, fg = '#bb9af7' })
vim.api.nvim_set_hl(0, 'DiffviewFilePanelFileName', { fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'DiffviewFilePanelTitle', { bold = true, fg = '#bb9af7' })
vim.api.nvim_set_hl(0, 'DiffviewPrimary', { fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, 'DiffviewSecondary', { fg = '#9ece6a' })
vim.api.nvim_set_hl(0, 'Directory', { fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, 'EndOfBuffer', { fg = '#24283b' })
vim.api.nvim_set_hl(0, 'Error', { fg = '#db4b4b' })
vim.api.nvim_set_hl(0, 'ErrorMsg', { fg = '#db4b4b' })
vim.api.nvim_set_hl(0, 'FlashBackdrop', { fg = '#545c7e' })
vim.api.nvim_set_hl(0, 'FlashLabel', { bg = '#ff007c', bold = true, fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'FloatBorder', { bg = '#1f2335', fg = '#29a4bd' })
vim.api.nvim_set_hl(0, 'FloatTitle', { bg = '#1f2335', fg = '#29a4bd' })
vim.api.nvim_set_hl(0, 'FoldColumn', { bg = '#24283b', fg = '#565f89' })
vim.api.nvim_set_hl(0, 'Folded', { bg = '#3b4261', fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, 'Foo', { bg = '#ff007c', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'Function', { fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, 'GitSignsAdd', { fg = '#266d6a' })
vim.api.nvim_set_hl(0, 'GitSignsChange', { fg = '#536c9e' })
vim.api.nvim_set_hl(0, 'GitSignsDelete', { fg = '#b2555b' })
vim.api.nvim_set_hl(0, 'GitSignsStagedAdd', { fg = '#133635' })
vim.api.nvim_set_hl(0, 'GitSignsStagedAddLn', { bg = '#283b4d' })
vim.api.nvim_set_hl(0, 'GitSignsStagedAddNr', { fg = '#133635' })
vim.api.nvim_set_hl(0, 'GitSignsStagedChange', { fg = '#29364f' })
vim.api.nvim_set_hl(0, 'GitSignsStagedChangeLn', { bg = '#272d43' })
vim.api.nvim_set_hl(0, 'GitSignsStagedChangeNr', { fg = '#29364f' })
vim.api.nvim_set_hl(0, 'GitSignsStagedChangedelete', { fg = '#29364f' })
vim.api.nvim_set_hl(0, 'GitSignsStagedChangedeleteLn', { bg = '#272d43' })
vim.api.nvim_set_hl(0, 'GitSignsStagedChangedeleteNr', { fg = '#29364f' })
vim.api.nvim_set_hl(0, 'GitSignsStagedDelete', { fg = '#592a2d' })
vim.api.nvim_set_hl(0, 'GitSignsStagedDeleteNr', { fg = '#592a2d' })
vim.api.nvim_set_hl(0, 'GitSignsStagedTopdelete', { fg = '#592a2d' })
vim.api.nvim_set_hl(0, 'GitSignsStagedTopdeleteNr', { fg = '#592a2d' })
vim.api.nvim_set_hl(0, 'Headline', { link = 'Headline1' })
vim.api.nvim_set_hl(0, 'Headline1', { bg = '#282e44' })
vim.api.nvim_set_hl(0, 'Headline2', { bg = '#2d2f3d' })
vim.api.nvim_set_hl(0, 'Headline3', { bg = '#2a303d' })
vim.api.nvim_set_hl(0, 'Headline4', { bg = '#232f40' })
vim.api.nvim_set_hl(0, 'Headline5', { bg = '#2c2e44' })
vim.api.nvim_set_hl(0, 'Headline6', { bg = '#2a2c43' })
vim.api.nvim_set_hl(0, 'Hlargs', { fg = '#e0af68' })
vim.api.nvim_set_hl(0, 'HopNextKey', { bold = true, fg = '#ff007c' })
vim.api.nvim_set_hl(0, 'HopNextKey1', { bold = true, fg = '#0db9d7' })
vim.api.nvim_set_hl(0, 'HopNextKey2', { fg = '#167f99' })
vim.api.nvim_set_hl(0, 'HopPreview', { link = 'IncSearch' })
vim.api.nvim_set_hl(0, 'HopUnmatched', { fg = '#545c7e' })
vim.api.nvim_set_hl(0, 'IblIndent', { fg = '#3b4261', nocombine = true })
vim.api.nvim_set_hl(0, 'IblScope', { fg = '#9d7cd8', nocombine = true })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '#bb9af7' })
vim.api.nvim_set_hl(0, 'IncSearch', { bg = '#ff9e64', fg = '#1d202f' })
vim.api.nvim_set_hl(0, 'IndentBlanklineChar', { fg = '#3b4261', nocombine = true })
vim.api.nvim_set_hl(0, 'IndentBlanklineContextChar', { fg = '#9d7cd8', nocombine = true })
vim.api.nvim_set_hl(0, 'Italic', { italic = true })
vim.api.nvim_set_hl(0, 'Keyword', { fg = '#7dcfff', italic = true })
vim.api.nvim_set_hl(0, 'LazyProgressDone', { bold = true, fg = '#ff007c' })
vim.api.nvim_set_hl(0, 'LazyProgressTodo', { bold = true, fg = '#3b4261' })
vim.api.nvim_set_hl(0, 'LineNr', { fg = '#3b4261' })
vim.api.nvim_set_hl(0, 'LspCodeLens', { fg = '#565f89' })
vim.api.nvim_set_hl(0, 'LspFloatWinBorder', { fg = '#29a4bd' })
vim.api.nvim_set_hl(0, 'LspFloatWinNormal', { bg = '#1f2335' })
vim.api.nvim_set_hl(0, 'LspInfoBorder', { bg = '#1f2335', fg = '#29a4bd' })
vim.api.nvim_set_hl(0, 'LspInlayHint', { bg = '#262c40', fg = '#545c7e' })
vim.api.nvim_set_hl(0, 'LspKindArray', { link = '@punctuation.bracket' })
vim.api.nvim_set_hl(0, 'LspKindBoolean', { link = '@boolean' })
vim.api.nvim_set_hl(0, 'LspKindClass', { link = '@type' })
vim.api.nvim_set_hl(0, 'LspKindColor', { link = 'Special' })
vim.api.nvim_set_hl(0, 'LspKindConstant', { link = '@constant' })
vim.api.nvim_set_hl(0, 'LspKindConstructor', { link = '@constructor' })
vim.api.nvim_set_hl(0, 'LspKindEnum', { link = '@lsp.type.enum' })
vim.api.nvim_set_hl(0, 'LspKindEnumMember', { link = '@lsp.type.enumMember' })
vim.api.nvim_set_hl(0, 'LspKindEvent', { link = 'Special' })
vim.api.nvim_set_hl(0, 'LspKindField', { link = '@field' })
vim.api.nvim_set_hl(0, 'LspKindFile', { link = 'Normal' })
vim.api.nvim_set_hl(0, 'LspKindFolder', { link = 'Directory' })
vim.api.nvim_set_hl(0, 'LspKindFunction', { link = '@function' })
vim.api.nvim_set_hl(0, 'LspKindInterface', { link = '@lsp.type.interface' })
vim.api.nvim_set_hl(0, 'LspKindKey', { link = '@field' })
vim.api.nvim_set_hl(0, 'LspKindKeyword', { link = '@lsp.type.keyword' })
vim.api.nvim_set_hl(0, 'LspKindMethod', { link = '@method' })
vim.api.nvim_set_hl(0, 'LspKindModule', { link = '@namespace' })
vim.api.nvim_set_hl(0, 'LspKindNamespace', { link = '@namespace' })
vim.api.nvim_set_hl(0, 'LspKindNull', { link = '@constant.builtin' })
vim.api.nvim_set_hl(0, 'LspKindNumber', { link = '@number' })
vim.api.nvim_set_hl(0, 'LspKindObject', { link = '@constant' })
vim.api.nvim_set_hl(0, 'LspKindOperator', { link = '@operator' })
vim.api.nvim_set_hl(0, 'LspKindPackage', { link = '@namespace' })
vim.api.nvim_set_hl(0, 'LspKindProperty', { link = '@property' })
vim.api.nvim_set_hl(0, 'LspKindReference', { link = '@text.reference' })
vim.api.nvim_set_hl(0, 'LspKindSnippet', { link = 'Conceal' })
vim.api.nvim_set_hl(0, 'LspKindString', { link = '@string' })
vim.api.nvim_set_hl(0, 'LspKindStruct', { link = '@lsp.type.struct' })
vim.api.nvim_set_hl(0, 'LspKindText', { link = '@text' })
vim.api.nvim_set_hl(0, 'LspKindTypeParameter', { link = '@lsp.type.typeParameter' })
vim.api.nvim_set_hl(0, 'LspKindUnit', { link = '@lsp.type.struct' })
vim.api.nvim_set_hl(0, 'LspKindValue', { link = '@string' })
vim.api.nvim_set_hl(0, 'LspKindVariable', { link = '@variable' })
vim.api.nvim_set_hl(0, 'LspReferenceRead', { bg = '#3b4261' })
vim.api.nvim_set_hl(0, 'LspReferenceText', { bg = '#3b4261' })
vim.api.nvim_set_hl(0, 'LspReferenceWrite', { bg = '#3b4261' })
vim.api.nvim_set_hl(0, 'LspSignatureActiveParameter', { bg = '#28304b', bold = true })
vim.api.nvim_set_hl(0, 'MatchParen', { bold = true, fg = '#ff9e64' })
vim.api.nvim_set_hl(0, 'MiniCompletionActiveParameter', { underline = true })
vim.api.nvim_set_hl(0, 'MiniCursorword', { bg = '#3b4261' })
vim.api.nvim_set_hl(0, 'MiniCursorwordCurrent', { bg = '#3b4261' })
vim.api.nvim_set_hl(0, 'MiniIndentscopePrefix', { nocombine = true })
vim.api.nvim_set_hl(0, 'MiniIndentscopeSymbol', { fg = '#2ac3de', nocombine = true })
vim.api.nvim_set_hl(0, 'MiniStarterCurrent', { nocombine = true })
vim.api.nvim_set_hl(0, 'MiniStarterFooter', { fg = '#e0af68', italic = true })
vim.api.nvim_set_hl(0, 'MiniStarterHeader', { fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, 'MiniStarterInactive', { fg = '#565f89', italic = true })
vim.api.nvim_set_hl(0, 'MiniStarterItem', { bg = '#24283b', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'MiniStarterItemBullet', { fg = '#29a4bd' })
vim.api.nvim_set_hl(0, 'MiniStarterItemPrefix', { fg = '#e0af68' })
vim.api.nvim_set_hl(0, 'MiniStarterQuery', { fg = '#0db9d7' })
vim.api.nvim_set_hl(0, 'MiniStarterSection', { fg = '#2ac3de' })
vim.api.nvim_set_hl(0, 'MiniStatuslineDevinfo', { bg = '#292e42', fg = '#a9b1d6' })
vim.api.nvim_set_hl(0, 'MiniStatuslineFileinfo', { bg = '#292e42', fg = '#a9b1d6' })
vim.api.nvim_set_hl(0, 'MiniStatuslineFilename', { bg = '#3b4261', fg = '#a9b1d6' })
vim.api.nvim_set_hl(0, 'MiniStatuslineInactive', { bg = '#1f2335', fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, 'MiniStatuslineModeCommand', { bg = '#e0af68', bold = true, fg = '#1d202f' })
vim.api.nvim_set_hl(0, 'MiniStatuslineModeInsert', { bg = '#9ece6a', bold = true, fg = '#1d202f' })
vim.api.nvim_set_hl(0, 'MiniStatuslineModeNormal', { bg = '#7aa2f7', bold = true, fg = '#1d202f' })
vim.api.nvim_set_hl(0, 'MiniStatuslineModeOther', { bg = '#1abc9c', bold = true, fg = '#1d202f' })
vim.api.nvim_set_hl(0, 'MiniStatuslineModeReplace', { bg = '#f7768e', bold = true, fg = '#1d202f' })
vim.api.nvim_set_hl(0, 'MiniStatuslineModeVisual', { bg = '#bb9af7', bold = true, fg = '#1d202f' })
vim.api.nvim_set_hl(0, 'MiniSurround', { bg = '#ff9e64', fg = '#1d202f' })
vim.api.nvim_set_hl(0, 'MiniTablineCurrent', { bg = '#3b4261', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'MiniTablineFill', { bg = '#1d202f' })
vim.api.nvim_set_hl(0, 'MiniTablineHidden', { bg = '#1f2335', fg = '#737aa2' })
vim.api.nvim_set_hl(0, 'MiniTablineModifiedCurrent', { bg = '#3b4261', fg = '#e0af68' })
vim.api.nvim_set_hl(0, 'MiniTablineModifiedHidden', { bg = '#1f2335', fg = '#a8875b' })
vim.api.nvim_set_hl(0, 'MiniTablineModifiedVisible', { bg = '#1f2335', fg = '#e0af68' })
vim.api.nvim_set_hl(0, 'MiniTablineTabpagesection', { bg = '#1f2335' })
vim.api.nvim_set_hl(0, 'MiniTablineVisible', { bg = '#1f2335', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'MiniTrailspace', { bg = '#f7768e' })
vim.api.nvim_set_hl(0, 'ModeMsg', { bold = true, fg = '#a9b1d6' })
vim.api.nvim_set_hl(0, 'MoreMsg', { fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, 'MsgArea', { fg = '#a9b1d6' })
vim.api.nvim_set_hl(0, 'NonText', { fg = '#545c7e' })
vim.api.nvim_set_hl(0, 'Normal', { bg = '#24283b', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'NormalFloat', { bg = '#1f2335', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'NormalNC', { bg = '#24283b', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'NormalSB', { bg = '#1f2335', fg = '#a9b1d6' })
vim.api.nvim_set_hl(0, 'NotifyBackground', { bg = '#24283b', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'NotifyDEBUGBody', { bg = '#24283b', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'NotifyDEBUGBorder', { bg = '#24283b', fg = '#333952' })
vim.api.nvim_set_hl(0, 'NotifyDEBUGIcon', { fg = '#565f89' })
vim.api.nvim_set_hl(0, 'NotifyDEBUGTitle', { fg = '#565f89' })
vim.api.nvim_set_hl(0, 'NotifyERRORBody', { bg = '#24283b', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'NotifyERRORBorder', { bg = '#24283b', fg = '#5b3340' })
vim.api.nvim_set_hl(0, 'NotifyERRORIcon', { fg = '#db4b4b' })
vim.api.nvim_set_hl(0, 'NotifyERRORTitle', { fg = '#db4b4b' })
vim.api.nvim_set_hl(0, 'NotifyINFOBody', { bg = '#24283b', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'NotifyINFOBorder', { bg = '#24283b', fg = '#1d546a' })
vim.api.nvim_set_hl(0, 'NotifyINFOIcon', { fg = '#0db9d7' })
vim.api.nvim_set_hl(0, 'NotifyINFOTitle', { fg = '#0db9d7' })
vim.api.nvim_set_hl(0, 'NotifyTRACEBody', { bg = '#24283b', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'NotifyTRACEBorder', { bg = '#24283b', fg = '#48416a' })
vim.api.nvim_set_hl(0, 'NotifyTRACEIcon', { fg = '#9d7cd8' })
vim.api.nvim_set_hl(0, 'NotifyTRACETitle', { fg = '#9d7cd8' })
vim.api.nvim_set_hl(0, 'NotifyWARNBody', { bg = '#24283b', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'NotifyWARNBorder', { bg = '#24283b', fg = '#5c5149' })
vim.api.nvim_set_hl(0, 'NotifyWARNIcon', { fg = '#e0af68' })
vim.api.nvim_set_hl(0, 'NotifyWARNTitle', { fg = '#e0af68' })
vim.api.nvim_set_hl(0, 'Operator', { fg = '#89ddff' })
vim.api.nvim_set_hl(0, 'Pmenu', { bg = '#1f2335', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'PmenuSbar', { bg = '#2a2e3f' })
vim.api.nvim_set_hl(0, 'PmenuSel', { bg = '#363d59' })
vim.api.nvim_set_hl(0, 'PmenuThumb', { bg = '#3b4261' })
vim.api.nvim_set_hl(0, 'PmenuKindSel', { link = 'PmenuSel' })
vim.api.nvim_set_hl(0, 'PmenuExtraSel', { link = 'PmenuSel' })
vim.api.nvim_set_hl(0, 'PmenuExtra', { link = 'Pmenu' })
vim.api.nvim_set_hl(0, 'PreProc', { fg = '#7dcfff' })
vim.api.nvim_set_hl(0, 'Question', { fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, 'QuickFixLine', { bg = '#2e3c64', bold = true })
vim.api.nvim_set_hl(0, 'Search', { bg = '#3d59a1', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'SignColumn', { bg = '#24283b', fg = '#3b4261' })
vim.api.nvim_set_hl(0, 'SignColumnSB', { bg = '#1f2335', fg = '#3b4261' })
vim.api.nvim_set_hl(0, 'Special', { fg = '#2ac3de' })
vim.api.nvim_set_hl(0, 'SpecialKey', { fg = '#545c7e' })
vim.api.nvim_set_hl(0, 'SpellBad', { sp = '#db4b4b', undercurl = true })
vim.api.nvim_set_hl(0, 'SpellCap', { sp = '#e0af68', undercurl = true })
vim.api.nvim_set_hl(0, 'SpellLocal', { sp = '#0db9d7', undercurl = true })
vim.api.nvim_set_hl(0, 'SpellRare', { sp = '#1abc9c', undercurl = true })
vim.api.nvim_set_hl(0, 'Statement', { fg = '#bb9af7' })
vim.api.nvim_set_hl(0, 'StatusLine', { bg = '#1f2335', fg = '#a9b1d6' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { bg = '#1f2335', fg = '#3b4261' })
vim.api.nvim_set_hl(0, 'String', { fg = '#9ece6a' })
vim.api.nvim_set_hl(0, 'Substitute', { bg = '#f7768e', fg = '#1d202f' })
vim.api.nvim_set_hl(0, 'TSNodeKey', { bold = true, fg = '#ff007c' })
vim.api.nvim_set_hl(0, 'TSNodeUnmatched', { fg = '#545c7e' })
vim.api.nvim_set_hl(0, 'TabLine', { bg = '#1f2335', fg = '#3b4261' })
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = '#1d202f' })
vim.api.nvim_set_hl(0, 'TabLineSel', { bg = '#7aa2f7', fg = '#1d202f' })
vim.api.nvim_set_hl(0, 'Title', { bold = true, fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, 'Todo', { bg = '#e0af68', fg = '#24283b' })
vim.api.nvim_set_hl(0, 'TreesitterContext', { bg = '#363d59' })
vim.api.nvim_set_hl(0, 'Type', { fg = '#2ac3de' })
vim.api.nvim_set_hl(0, 'VertSplit', { fg = '#1d202f' })
vim.api.nvim_set_hl(0, 'Visual', { bg = '#2e3c64' })
vim.api.nvim_set_hl(0, 'VisualNOS', { bg = '#2e3c64' })
vim.api.nvim_set_hl(0, 'WarningMsg', { fg = '#e0af68' })
vim.api.nvim_set_hl(0, 'Whitespace', { fg = '#3b4261' })
vim.api.nvim_set_hl(0, 'WildMenu', { bg = '#2e3c64' })
vim.api.nvim_set_hl(0, 'WinSeparator', { bold = true, fg = '#1d202f' })
vim.api.nvim_set_hl(0, 'debugBreakpoint', { bg = '#22374b', fg = '#0db9d7' })
vim.api.nvim_set_hl(0, 'debugPC', { bg = '#1f2335' })
vim.api.nvim_set_hl(0, 'diffAdded', { fg = '#449dab' })
vim.api.nvim_set_hl(0, 'diffChanged', { fg = '#6183bb' })
vim.api.nvim_set_hl(0, 'diffFile', { fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, 'diffIndexLine', { fg = '#bb9af7' })
vim.api.nvim_set_hl(0, 'diffLine', { fg = '#565f89' })
vim.api.nvim_set_hl(0, 'diffNewFile', { fg = '#ff9e64' })
vim.api.nvim_set_hl(0, 'diffOldFile', { fg = '#e0af68' })
vim.api.nvim_set_hl(0, 'diffRemoved', { fg = '#914c54' })
vim.api.nvim_set_hl(0, 'dosIniLabel', { link = '@property' })
vim.api.nvim_set_hl(0, 'healthError', { fg = '#db4b4b' })
vim.api.nvim_set_hl(0, 'healthSuccess', { fg = '#73daca' })
vim.api.nvim_set_hl(0, 'healthWarning', { fg = '#e0af68' })
vim.api.nvim_set_hl(0, 'helpCommand', { bg = '#414868', fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, 'htmlH1', { bold = true, fg = '#bb9af7' })
vim.api.nvim_set_hl(0, 'htmlH2', { bold = true, fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, 'lCursor', { bg = '#c0caf5', fg = '#24283b' })
vim.api.nvim_set_hl(0, 'markdownCode', { fg = '#1abc9c' })
vim.api.nvim_set_hl(0, 'markdownCodeBlock', { fg = '#1abc9c' })
vim.api.nvim_set_hl(0, 'markdownH1', { bold = true, fg = '#bb9af7' })
vim.api.nvim_set_hl(0, 'markdownH2', { bold = true, fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, 'markdownHeadingDelimiter', { bold = true, fg = '#ff9e64' })
vim.api.nvim_set_hl(0, 'markdownLinkText', { fg = '#7aa2f7', underline = true })
vim.api.nvim_set_hl(0, 'mkdCodeDelimiter', { bg = '#414868', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'mkdCodeEnd', { bold = true, fg = '#1abc9c' })
vim.api.nvim_set_hl(0, 'mkdCodeStart', { bold = true, fg = '#1abc9c' })
vim.api.nvim_set_hl(0, 'qfFileName', { fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, 'qfLineNr', { fg = '#737aa2' })

vim.g.terminal_color_0 = '#1d202f'
vim.g.terminal_color_1 = '#f7768e'
vim.g.terminal_color_2 = '#9ece6a'
vim.g.terminal_color_3 = '#e0af68'
vim.g.terminal_color_4 = '#7aa2f7'
vim.g.terminal_color_5 = '#bb9af7'
vim.g.terminal_color_6 = '#7dcfff'
vim.g.terminal_color_7 = '#a9b1d6'
vim.g.terminal_color_8 = '#414868'
vim.g.terminal_color_9 = '#f7768e'
vim.g.terminal_color_10 = '#9ece6a'
vim.g.terminal_color_11 = '#e0af68'
vim.g.terminal_color_12 = '#7aa2f7'
vim.g.terminal_color_13 = '#bb9af7'
vim.g.terminal_color_14 = '#7dcfff'
vim.g.terminal_color_15 = '#c0caf5'
